name = "stock-research-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

# KV namespace for caching
[[kv_namespaces]]
binding = "CACHE"
id = "5215ef430db54824a7da3369e5129399"
preview_id = "11107235a816466c993f354b3bdc72a4"

# Environment variables (set via wrangler secret put)
# MARKETSTACK_API_KEY - set this using: wrangler secret put MARKETSTACK_API_KEY

[env.production]
workers_dev = false
route = "my-stock-api.stock-research-api.workers.dev/*"

[env.development]
vars = { ENVIRONMENT = "development" }

